//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarwarsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class planet
    {
        public planet()
        {
            this.films = new HashSet<film>();
        }
    
        public int id { get; set; }
        public string climate { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string diameter { get; set; }
        public Nullable<System.DateTime> edited { get; set; }
        public string gravity { get; set; }
        public string name { get; set; }
        public string orbital_period { get; set; }
        public string population { get; set; }
        public string rotation_period { get; set; }
        public string surface_water { get; set; }
        public string terrain { get; set; }
    
        public virtual ICollection<film> films { get; set; }
    }
}
