//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarwarsAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class starship
    {
        public starship()
        {
            this.people = new HashSet<person>();
        }
    
        public int id { get; set; }
        public string MGLT { get; set; }
        public string hyperdrive_rating { get; set; }
        public string starship_class { get; set; }
    
        public virtual ICollection<person> people { get; set; }
    }
}
